import { VideoArtProjectType } from "projects/types";
import { mediaEndPoint } from "../config"

export const Project: VideoArtProjectType = {    category: `visual`,
    id: 141,
    name: `Gatsby in Motion - Teaser`,
    author: `Bertrand Normand`,
    subcategory: `videoArt`,
    tags: [],
    video: `${mediaEndPoint}/media/141/Gatsby in Motion - Teaser.mp4`,
    description: `Parisien de naissance, je suis réalisateur de films, essentiellement de documentaires et de courts métrages de fiction. Mes films racontent la quête d’individus cherchant à atteindre une forme d’idéal, qu’il soit dans la sphère artistique, religieuse, politique ou sociale. Jusqu’à présent, le plus connu est "Ballerina", un documentaire sur les ballerines du Théâtre Mariinski, qui est sorti il y a 12 ans et explore ce qu’est devenu le mythe de la ballerine après la chute de l’URSS. Parmi mes courts métrages, "La Photographe", thriller fantastique qui raconte la traque d’une statue par une photographe dans les jardins du château de Versailles, a participé à plus de 70 festivals et obtenu 13 prix.
Depuis longtemps je m’intéresse à l’espace post-soviétique et depuis 2003 j’y ai beaucoup voyagé et y ai réalisé plusieurs documentaires. Avant 2014, j’avais été peu en Ukraine, mais j’étais curieux de connaître ce pays davantage. En début 2014, j’ai été très impressionné par la résistance des Ukrainiens lors de la révolution de Maïdan et par la victoire qu’ils ont obtenue. Lors du Salon du Livre à Paris, j’ai discuté avec plusieurs auteurs ukrainiens qui avaient participé à cette révolution et m’ont expliqué comment ils l’avaient vécue de l’intérieur. Cela m’a permis de comprendre que des changements profonds étaient en train d’avoir lieu en Ukraine. J’ai donc décidé de m’y rendre et d’observer la situation de mes propres yeux. 
Une fois sur place, j’ai été frappé par l’énergie, la détermination et l’espoir en l’avenir de nombreuses personnes qui j’ai croisées ainsi que par les innombrables signes de patriotisme visibles partout dans le pays. J’ai compris qu’un phénomène majeur était en train de se produire en Ukraine : l’éveil d’un sentiment national chez de très nombreux individus qui jusqu’alors avaient été indifférents à cette question, indissociable de certaines valeurs, telles que la liberté, l’ouverture et l’état de droit. Il m’a semblé que ce phénomène méritait d’être documenté. J’ai donc cherché des personnages qui pouvaient au mieux exprimer cette prise de conscience et j’ai commencé à les filmer, avec l’intention de réaliser un film documentaire sur le sujet. 
Un tel projet, pour aboutir, doit nécessairement se faire avec le soutien d’une chaîne de télévision ou d’un distributeur, or après un bref intérêt des médias français pour l’Ukraine au moment de la révolution de Maïdan, l’intérêt s’est émoussé et il a été très difficile d’obtenir le soutien d’un diffuseur. J’ai quand même décidé de mener ce projet avec les moyens à ma disposition en espérant trouver plus tard des solutions financières pour terminer le travail et des débouchés pour que le film soit vu. 
Ainsi, pendant des années, j’ai voyagé régulièrement dans diverses régions et villes du pays et j’y ai filmé de nombreux Ukrainiens, hommes et femmes, de différents âges, qui par les choix qu’ils ont faits dans leur vie incarnent la prise de conscience de leur identité ukrainienne et l’acquisition des valeurs qui lui sont associées. Parmi eux, j’ai été particulièrement intéressé par les volontaires, ces citoyens qui à partir de 2014 ont agi bénévolement dans les domaines où l’état était déficient et ont tout simplement permis au pays de survivre, mais aussi par les réfugiés du Donbass et de Crimée qui se sont déplacés dans différentes régions de l’Ukraine et ont ainsi découvert davantage leur pays et l’on également fait davantage découvrir aux habitants qui les ont accueillis.
Ce documentaire, dont le titre devrait être "Ukraine, Naissance d’une Nation", répondra à la question que beaucoup se posent depuis quelques mois : Qu’est-ce qui incite les Ukrainiens à résister ainsi à un agresseur beaucoup plus puissant et où puisent-ils la force pour y parvenir ?
Il est actuellement en montage et nous attendons des réponses des diffuseurs à qui nous l’avons proposé. 
Un autre projet que j’ai tourné en Ukraine est un documentaire sur la création du ballet contemporain "The Great Gatsby", qui a été monté et représenté à Kyiv un an après la révolution de Maïdan et qui a été le fruit d’une collaboration entre artistes Ukrainiens et Américains. Depuis longtemps je souhaitais consacrer un film à la création d’un spectacle chorégraphique, or celui-ci m’a semblé particulièrement intéressant en raison du contexte dans lequel son éclosion s’est inscrite : celui d’un pays déjà en guerre qui essayait de survivre et où la danse semblait la dernière des priorités, mais où néanmoins la population avait besoin d’expériences lui permettant de rêver et de s’évader pour mieux supporter la situation. 
Par conséquent, lorsque j’ai appris que ce projet allait avoir lieu, j’ai demandé aux producteurs l’autorisation de filmer les répétitions, autorisation qu’ils m’ont accordée. J’ai suivi pas à pas le travail du chorégraphe, Dwight Rhoden, avec les danseurs, la création des mouvements, les répétitions de la musique originale de Konstantin Meladze par l’Orchestre Symphonique National d’Ukraine et la préparation du spectacle jusqu’à sa première au Palais de l’Ukraine. Le thème principal que ce film abordera sera la rencontre entre deux cultures de la danse, celle du Hip Hop venant des Etats-Unis et celle de la danse classique prévalent en Ukraine, et la façon dont ces deux cultures ont fusionné à l’occasion de la création de ce spectacle. "Gatsby in Motion" est actuellement en montage et j’espère le terminer d’ici quelques mois.
A partir de 2018, j’ai collaboré avec un producteur français qui m’a proposé de filmer des ballets de l’Opéra National d’Ukraine pour la télévision française. Nous avons d’abord filmé "Casse-Noisette", puis "Le Lac des Cygnes", qui sont tous deux sortis en home video et dont le second a été diffusé sur plusieurs chaînes française et a été largement rediffusé depuis le début de la guerre.
En plus de réaliser les captations de ces spectacles, j’ai décidé de filmer les artistes en coulisse avec l’idée de faire un documentaire sur cette troupe qui est la meilleure d’Ukraine et dont la notoriété était croissante à l’étranger, en particulier en France, où elle a en 2018 et 2019 effectué des tournées prestigieuses, et ce pour la première fois depuis plusieurs décennies. Le COVID a interrompu ce projet, puisque l’activité de la compagnie a quasiment cessé pendant toute la durée où il a sévi et que par ailleurs je n’ai pas pu me rendre en Ukraine pendant toute cette période. Puis la guerre a éclaté. 
Dès les premiers jours de l’offensive, la troupe de ballet de l’Opéra National d’Ukraine s’est disloquée car de nombreux artistes ont quitté Kyiv et un certain nombre sont partis à l’étranger. J’ai écrit à de nombreux danseurs pour prendre de leurs nouvelles et ils m’ont informé de l’évolution de leur situation. C’est alors que j’ai décidé de poursuivre le projet initié avant le COVID et de filmer la vie des artistes que j’avais déjà suivi à Kyiv et Paris au cours de leur exil forcé. J’en ai filmé quelques-uns au cours des derniers mois en Allemagne ainsi qu’aux Pays-Bas, où a été créé l’United Ukrainian Ballet, lequel regroupe des danseurs venant de différentes villes d’Ukraine qui ont fui la guerre. Il reste encore beaucoup à faire pour ce projet et j’espère en particulier filmer les nouveaux débuts de la troupe lorsque la guerre sera terminée.
La nation ukrainienne me semble aujourd’hui une nation très forte, elle est incontestablement la nation la plus forte d’Europe. Le courage, la détermination, la résilience qui l’animent depuis 2014 et lui permettent de se choisir son propre destin en dépit des tentatives de son grand voisin de l’asservir sont inégalées sur notre continent depuis la Seconde Guerre Mondiale. Pour tous les Européens ainsi que pour tous les amateurs de liberté dans le monde, c’est une fantastique source d’espoir et d’inspiration.

`,
}
export default Project;